#!/usr/bin/env python3
"""Render the Open Graph / social card for beets-ai.com → public/og-image.png (1200×630).

Text is drawn with PIL, never generated by an image model: an OG card is mostly
words, and diffusion text is garbled. Brand tokens match the site (red #e10707,
ink #080808, surface #f3f3f3).

Run:  python3 scripts/gen-og-image.py
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "og-image.png"
LOGO = ROOT / "public" / "beets-logo.png"

W, H = 1200, 630
RED = (225, 7, 7)
INK = (8, 8, 8)
MUTED = (111, 111, 111)
SURFACE = (243, 243, 243)

CJK = "/System/Library/Fonts/STHeiti Medium.ttc"
LATIN = "/System/Library/Fonts/HelveticaNeue.ttc"


def font(path: str, size: int, index: int = 0) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(path, size, index=index)


def main() -> None:
    img = Image.new("RGB", (W, H), (255, 255, 255))
    d = ImageDraw.Draw(img)

    # Left brand rule
    d.rectangle([0, 0, 10, H], fill=RED)

    # Logo + wordmark
    logo = Image.open(LOGO).convert("RGBA").resize((96, 96), Image.LANCZOS)
    img.paste(logo, (72, 64), logo)
    d.text((188, 88), "BEETS AI", font=font(LATIN, 46, index=1), fill=INK)
    d.text((190, 142), "beets-ai.com", font=font(LATIN, 24), fill=MUTED)

    # Headline (Traditional Chinese) + English counterpart
    d.text((74, 244), "香港免費 AI 教育資源", font=font(CJK, 82), fill=INK)
    d.text(
        (78, 362),
        "Free Hong Kong AI teaching resources",
        font=font(LATIN, 40),
        fill=(17, 109, 255),  # brand blue as the secondary accent
    )

    # Footer band
    d.rectangle([0, H - 96, W, H], fill=SURFACE)
    d.rectangle([72, H - 96, 72 + 96, H - 90], fill=RED)
    d.text(
        (74, H - 62),
        "免費下載 · 免註冊 · 經教育工作者審閱及事實核實",
        font=font(CJK, 28),
        fill=INK,
    )
    d.text((W - 74 - 232, H - 58), "Free · No sign-up", font=font(LATIN, 26), fill=MUTED)

    img.save(OUT, "PNG", optimize=True)
    print(f"wrote {OUT} — {OUT.stat().st_size} bytes, {img.size[0]}x{img.size[1]}")


if __name__ == "__main__":
    main()
